apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
  labels:
    app: iris-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8200
    protocol: TCP
  selector:
    app: iris-api
