name: CD Pipeline

on:
  push:
    branches:
      - main  # Triggers only on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 420.0.0'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use gcloud CLI
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          cd app
          REGISTRY_LOCATION="us-central1"
          IMAGE="iris-api"
          COMMIT_SHA="${{ github.sha }}"

          echo "Building Docker image..."
          docker build -t "$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:$COMMIT_SHA" .
          docker tag "$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:$COMMIT_SHA" \
                     "$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:latest"

      - name: Push Docker image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          REGISTRY_LOCATION="us-central1"
          IMAGE="iris-api"
          COMMIT_SHA="${{ github.sha }}"

          echo "Pushing Docker images..."
          docker push "$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:$COMMIT_SHA"
          docker push "$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:latest"

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get GKE credentials
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GKE_CLUSTER: iris-cluster
          GKE_ZONE: us-central1-a
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Deploy to GKE
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          REGISTRY_LOCATION="us-central1"
          IMAGE="iris-api"
          COMMIT_SHA="${{ github.sha }}"

          echo "Applying deployment..."
          sed "s|IMAGE_PLACEHOLDER|$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/my-repo/$IMAGE:$COMMIT_SHA|g" k8s/deployment.yaml | kubectl apply -f -
          kubectl apply -f k8s/service.yaml
